return array(
	'items'	=> array(
		array(
			'sublist'	=>	array(
	            'items'   => array(
	                array(
	                    'name'  =>  'Структура',
	                    'url'   =>  '/_backend/struct/',
	                    'alias' =>  'struct',
	                    'code'  =>  12
	                ),
	                array(
	                    'name'  =>  'Шаблоны',
	                    'url'   =>  '/_backend/templates/',
	                    'alias' =>  'templates',
	                    'code'  =>  13
	                ),
	            )
            )
		),
		array(
        	'sublist'	=>	array(
	            'items' => array(
	                array(
	                    'name'  =>  'Интерактив',
	                    'url'   =>  '/_backend/interactive/',
	                    'alias' =>  'interactive',
	                    'code'  =>  14
	                ),
	                array(
	                    'name'  =>  'Сервисы',
	                    'url'   =>  '/_backend/services/',
	                    'alias' =>  'services',
	                    'code'  =>  15
	                ),
	            )
            )
		),
		array(
        	'sublist'	=>	array(
	            'items'   => array(
	                array(
	                    'name'  =>  'Изображения',
	                    'url'   =>  '/_backend/images/',
	                    'alias' =>  'images',
	                    'code'  =>  16
	                ),
	                array(
	                    'name'  =>  'Файлы',
	                    'url'   =>  '/_backend/files/',
	                    'alias' =>  'files',
	                    'code'  =>  17
	                )
	            )
            )
		),
		array(
        	'sublist'	=>	array(
	            'items'   => array(
	                array(
	                    'name'  =>  'Модули',
	                    'url'   =>  '/_backend/modules/',
	                    'alias' =>  'modules',
	                    'code'  =>  18
	                ),
	                array(
	                    'name'  =>  'Система',
	                    'url'   =>  '/_backend/system/',
	                    'alias' =>  'system',
	                    'code'  =>  2
	                ),
	            )
            )
		),
	),
);