tinyMCE.addI18n('ru.advanced',{
style_select:"Стили",
font_size:"Размер шрифта",
fontdefault:"Гарнитура шрифта",
block:"Формат",
paragraph:"Параграф",
div:"Слой",
address:"Адрес",
pre:"Отформатированный",
h1:"Заголовок 1",
h2:"Заголовок 2",
h3:"Заголовок 3",
h4:"Заголовок 4",
h5:"Заголовок 5",
h6:"Заголовок 6",
blockquote:"Цитата",
code:"Код",
samp:"Пример",
dt:"Термин",
dd:"Значение термина",
bold_desc:"Полужирный (Ctrl+B)",
italic_desc:"Курсив (Ctrl+I)",
underline_desc:"Подчеркнутый (Ctrl+U)",
striketrough_desc:"Зачеркнутый",
justifyleft_desc:"По левому краю",
justifycenter_desc:"По центру",
justifyright_desc:"По правому краю",
justifyfull_desc:"По ширине",
bullist_desc:"Маркированный список",
numlist_desc:"Нумерованный список",
outdent_desc:"Выступ",
indent_desc:"Отступ",
undo_desc:"Отменить (Ctrl+Z)",
redo_desc:"Вернуть (Ctrl+Y)",
link_desc:"Вставить/редактировать гиперссылку",
unlink_desc:"Удалить гиперссылку",
image_desc:"Вставить/редактировать изображение",
cleanup_desc:"Убрать лишнюю разметку",
code_desc:"Редактировать исходный html-код",
sub_desc:"Подстрочный",
sup_desc:"Надстрочный",
hr_desc:"Вставить горизонтальную линию",
removeformat_desc:"Удалить форматирование",
custom1_desc:"Ваше описание",
forecolor_desc:"Цвет шрифта",
backcolor_desc:"Цвет фона",
charmap_desc:"Вставить символ",
visualaid_desc:"Скрыть/показать направляющие и невидимые элементы",
anchor_desc:"Вставить / Редактировать якорь",
cut_desc:"Вырезать",
copy_desc:"Скопировать",
paste_desc:"Вставить",
image_props_desc:"Свойства изображения",
newdocument_desc:"Новый документ",
help_desc:"Помощь",
blockquote_desc:"Цитата",
clipboard_msg:"Скопировать/Вырезать/вставить не доступны в Mozilla и Firefox.\r\nХотите получить более подробную информацию по этому вопросу?",
path:"Путь",
newdocument:"Вы уверены, что хотите удалить все содержимое?",
toolbar_focus:"Перейти к инструментов кнопки - Alt + Q, Перейти к редактору - Alt-Z, Перейти к элементу пути - Alt-X",
more_colors:"Дополнительные цвета"
});