tinyMCE.addI18n('ru.advanced_dlg',{
about_title:"About TinyMCE",
about_general:"About",
about_help:"Help",
about_license:"License",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Author",
about_version:"Version",
about_loaded:"Loaded plugins",
anchor_title:"Insert/edit anchor",
anchor_name:"Anchor name",
code_title:"HTML Source Editor",
code_wordwrap:"Word wrap",
colorpicker_title:"Select a color",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"Color picker",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palette colors",
colorpicker_named_tab:"Named",
colorpicker_named_title:"Named colors",
colorpicker_color:"Color:",
colorpicker_name:"Name:",
charmap_title:"Select custom character",
image_title:"Вставить / редактировать изображение",
image_src:"URL картинки",
image_alt:"Описание",
image_list:"Список изображений",
image_border:"Рамка",
image_dimensions:"Размеры",
image_vspace:"Отступ по вертикали",
image_hspace:"Отступ по горизонтали",
image_align:"Выравнивание",
image_align_baseline:"Baseline",
image_align_top:"По верхнему краю",
image_align_middle:"По центру",
image_align_bottom:"По нижнему краю",
image_align_texttop:"Text top",
image_align_textbottom:"Text bottom",
image_align_left:"По левому краю",
image_align_right:"По правому краю",
link_title:"Вставить / редактировать ссылку",
link_url:"URL ссылки",
link_target:"Открыть ссылку",
link_target_same:"В том же окне",
link_target_blank:"В новом окне",
link_titlefield:"Заголовок",
link_is_email:"Вы ввели URL-видимому, является адрес электронной почты, вы хотите добавить необходимый Mailto: префикс?",
link_is_external:"URL Вы вступили кажется внешние ссылки, вы хотите добавить необходимый префикс http://?",
link_list:"Список ссылок",
link_class_name: "Класс"
});